import Head from 'next/head';

import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

const getData = () => {

}

export default function Home() {
  return (
    <>
      <Head>
        <title>Snapseeker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex gap-2">
          <a
            href="/auth/sign-up"
            className="hover:bg-primary-dark focus:ring-primary-light focus:border-primary-darkest active:bg-primary-darkest flex justify-center rounded-md border border-transparent bg-cyan-800 py-2 px-4 text-sm font-medium text-white transition duration-150 ease-in-out focus:outline-none focus:ring-4"
          >
            Sign up
          </a>
          <a
            href="/auth/login"
            className="hover:bg-primary-dark focus:ring-primary-light focus:border-primary-darkest active:bg-primary-darkest flex justify-center rounded-md border border-transparent bg-cyan-800 py-2 px-4 text-sm font-medium text-white transition duration-150 ease-in-out focus:outline-none focus:ring-4"
          >
            Login
          </a>
            </div>

          <div className='flex h-screen w-screen items-center justify-center'>
            <div className='flex flex-col items-center gap-6'>
              <input
              type='text'
              className='rounded-md border-2 border-gray-300 p-2'
              placeholder='Enter UPC'
              />
              <button onClick={getData} type='button' className='rounded-md bg-pink-600 p-4 text-x1 front-bold'>
                Go
              </button>
          </div>
        </div>
      </main>
    </>
  );
}
